EHMS/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "EHMSAPP"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("EHMSAPP.urls")),
]

EHMSAPP/urls.py
from django.urls import path

from EHMSAPP import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "EHMSAPP"

urlpatterns = [
    path("", views.home),
    path("appointments", views.supervisor_appointments),
    path("patients", views.supervisor_patients),
    path("prescriptions", views.supervisor_prescriptions),
    path("login/", views.login_request),
    path("doctors/", views.get_all_doctors),
    path("logout/", views.logout_request),
    path("register/doctor", views.register_doctor),
    path("register/patient", views.register_patient),
    path("doctor/<str:username>", views.doctor_profile, name="doctor_profile"),
    path("patient/<str:username>", views.patient_profile, name="patient_profile"),
    path("patient/<str:username>/edit", views.edit_profile, name="edit_profile"),
    path("patient/<str:username>/delete", views.delete_profile, name="delete_profile"),
    path("doctor/<str:username>/edit", views.edit_doc, name="edit_doc"),
    path("doctor/<str:username>/delete", views.delete_doc, name="delete_doc"),
    path("doctor/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("doctor/<str:username>/appointments/<str:month>", views.CalendarView.as_view(), name="calendar"),
    path("patient/<str:username>/appointments", views.patient_appointments),
    path("patient/<str:username>/appointments/<int:appointment_id>/pay", views.pay_for_appointment),
    path("patient/<str:username>/appointments/<int:appointment_id>/edit", views.edit_appointment, name="edit_appointment"),
    path("patient/<str:username>/appointments/<int:appointment_id>/delete", views.delete_appointment, name="delete_appointment"),
    path("patient/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("forgot_password", views.forgot_password),
    path("patient/<str:username>/prescriptions", views.patient_prescriptions),
    path("patient/<str:username>/prescriptions/add", views.add_prescriptions),
    path("patient/<str:username>/prescriptions/<int:prescription_id>/delete", views.delete_prescriptions, name="delete_prescription"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/doctors/appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Appointments</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<style>
    .calendar {
        width: 85%;
        font-size: 13px;
        margin: 15px auto auto;
    }

    .calendar tr, .calendar td {
        border: 1px solid black;
    }

    .calendar th {
        padding: 10px;
        text-align: center;
        font-size: 18px;
    }

    .calendar td {
        width: 150px;
        height: 150px;
        padding: 20px 0 0 5px;
    }

    .month {
        font-size: 25px;
    }

    .date {
        font-size: 16px;
    }

    ul {
        height: 100%;
        padding: 0 5px 0 20px;
    }

    .left {
        float: left;
    }

    .right {
        float: right;
    }

    .clearfix {
        margin: 15px;
    }

</style>
<body>
{% include "nav_bars/logged_in_nav_bar.html" %}
{% block content %}
    <div class="clearfix">
        <a class="btn btn-outline-success left" style="margin-left: 7%"
           href="{% url 'EHMSAPP:calendar' username=username month=prev_month %}"> Previous Month </a>
        <a class="btn btn-outline-success right" style="margin-right: 7%"
           href="{% url 'EHMSAPP:calendar' username=username month=next_month %}"> Next Month </a>
    </div>
    {{ calendar }}
{% endblock %}
</body>
</html>

templates/doctors/edit_doc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Edit Profile</title>
</head>
<body class="bg-light">
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% endif %}
<div class="container">
    <div class="py-5 text-center">
        <h1 id="formTitle">Edit Doctor's profile</h1>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: auto; margin-right: 100px">
        <form class="row g-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-md-5">
                    <label class="form-label"> {{ field.label }} </label>
                    {{ field }}
                </div>
            {% endfor %}
            <ul class="row" style="margin-left: 15px">
                <li class="col-5">Password must contain at least 8 characters</li>
                <li class="col-5">Password should not include user's info</li>
                <li class="col-5">Password should not be common</li>
                <li class="col-5">Password should not be entirely numeric</li>
            </ul>
            <div>
                <br>
                <button type="submit" class="btn btn-primary">Edit Profile</button>
            </div>
            <hr>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

<script>

    var doctorCheck = document.getElementById("id_is_doctor")
    doctorCheck.style.display = "none"
    document.getElementById("id_security_question").placeholder = "What was the name of your favorite teacher?"
    document.getElementById("id_birthday").type = "date"
    document.getElementById("id_gender").className = "form-select"
    var labels = document.getElementsByTagName('label');
    for (let i = 0; i < labels.length; i++) {
        if (labels[i].innerText.includes("Is doctor")) {
            labels[i].parentElement.style.display = "none";
            break
        }
    }
    var inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
    document.getElementById("photo-clear_id").className = ""
    if (window.location.toString().includes("doctor")) {
        document.getElementById("id_specialization").className = "form-select"
        document.getElementById("formTitle").innerText = "Register Doctor"
        document.getElementById("doctorSignup").innerText = "Are you a patient?"
        document.getElementById("singupLink").href = "/register/patient"
        document.getElementById("singupLink").innerText = "Sign Up here"
        doctorCheck.checked = true
    } else {
        document.getElementById("id_security_question").parentElement.className = "form-group"
        document.getElementById("id_security_question").parentElement.style.width = "83%"
        document.getElementById("id_security_question").className = "form-control"
    }

</script>

templates/doctors/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css">

    <style>
        body {
            background-color: #eee
        }

        .team-button button {
            font-size: 12px;
            width: 180px;
            height: 40px
        }

        .team-projects span {
            font-size: 12px;
            width: 250px;
            height: 40px;
            border: 1px solid #d4d2d2;
            background-color: #eee;
            border-radius: 4px;
            padding: 10px 23px;
        }
    </style>
    <title>Doctor</title>
</head>
<body>
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% elif request.user.is_authenticated %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_out_nav_bar.html" %}
{% endif %}
<div class="container d-flex justify-content-center align-items-center mt-5 mb-5">
    <div class="card mb-5" style="width: 40rem;">
        <div class="p-2">
            <div class="d-flex flex-row ml-5 mt-4">
                {% if doctor.photo %}
                    <img class="rounded-circle" src="{{ doctor.photo.url }}" width="80" height="80" alt="PP">
                {% else %}
                    <img src="../../media/default_pic.jpg" class="rounded-circle" width="70" alt="Default PP">
                {% endif %}
                <div class="d-flex flex-column ml-5 mt-4"><span
                        style="font-weight: bold; font-size: 22px">Doctor Profile: Dr. {{ doctor.first_name }} {{ doctor.last_name }}</span>
                </div>


            </div>
            <div class="mt-4"><span class="ml-2" style="font-weight: bold">Doctor's Schedule</span>
                <div class="mt-2 team-button d-flex justify-content-between px-2">
                    <a href="{% url 'EHMSAPP:calendar' username=doctor.username month=month %}">
                        <button class="btn btn-primary ml-1">Check Schedule</button>
                    </a>
                </div>
            </div>
            <div class="mt-4"><span class="ml-2" style="font-weight: bold">Specialization</span>
                <div class="mt-3 team-projects d-flex justify-content-between px-2">
                    <span>{{ doctor.specialization }}</span></div>
            </div>
        </div>
        <div class=" mt-3 mb-3"><span class="ml-2 mb-3" style="font-weight: bold">Personal Information</span>
            <hr class="m-0 mt-1">
        </div>
        <div class="d-flex flex-row justify-content-between px-3">
            <div class="d-flex flex-column ml-2"><span>Phone</span>
                <div class="mt-2 team-projects d-flex justify-content-between px-0">
                    <span>{{ doctor.phone_number }}</span></div>
            </div>
            <div class="d-flex flex-column ml-2"><span>Email</span>
                <div class="mt-2 team-projects d-flex justify-content-between px-0"><span>{{ doctor.email }}</span>
                </div>
            </div>
        </div>
        <div class="d-flex flex-row justify-content-between px-3 mb-3 mt-3">
            <div class="d-flex flex-column ml-2"><span>City</span>
                <div class="mt-2 team-projects d-flex justify-content-between px-0"><span>{{ doctor.city }}</span></div>
            </div>
            <div class="d-flex flex-column ml-2"><span>Address</span>
                <div class="mt-2 team-projects d-flex justify-content-between px-0"><span>{{ doctor.address }}</span>
                </div>
            </div>
        </div>
        {% if flag %}
            <div class="mt-4 mb-3"><span class="ml-3" style="font-weight: bold">Edit Profile</span>
            <div class="mt-2 team-button d-flex justify-content-between px-3">
                <a href="{% url 'EHMSAPP:edit_doc' doctor.username %}">
                    <button class="btn btn-primary ml-1">Edit</button>
                </a>
            </div>
            <div class="mt-2 team-button d-flex justify-content-between px-3">
                <a href="{% url 'EHMSAPP:delete_doc' doctor.username %}">
                    <button class="btn btn-primary ml-1">Delete</button>
                </a>
            </div>
        {% endif %}
        {% if request.user.is_authenticated and not is_doctor %}
            <div class="mt-4 mb-3"><span class="ml-3"
                                         style="font-weight: bold">Schedule a meeting with Dr. {{ doctor.first_name }} {{ doctor.last_name }} </span>
                <div class="mt-2 team-button d-flex justify-content-between px-3"><a
                        href="{% url 'EHMSAPP:add_appointment' doctor.username %}">
                    <button class="btn btn-primary ml-1">Click to Schedule</button>
                </a></div>
            </div>
        {% endif %}
        </div>

    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>