EHMS/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "EHMSAPP"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("EHMSAPP.urls")),
]

EHMSAPP/urls.py
from django.urls import path

from EHMSAPP import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "EHMSAPP"

urlpatterns = [
    path("", views.home),
    path("appointments", views.supervisor_appointments),
    path("patients", views.supervisor_patients),
    path("prescriptions", views.supervisor_prescriptions),
    path("login/", views.login_request),
    path("doctors/", views.get_all_doctors),
    path("logout/", views.logout_request),
    path("register/doctor", views.register_doctor),
    path("register/patient", views.register_patient),
    path("doctor/<str:username>", views.doctor_profile, name="doctor_profile"),
    path("patient/<str:username>", views.patient_profile, name="patient_profile"),
    path("patient/<str:username>/edit", views.edit_profile, name="edit_profile"),
    path("patient/<str:username>/delete", views.delete_profile, name="delete_profile"),
    path("doctor/<str:username>/edit", views.edit_doc, name="edit_doc"),
    path("doctor/<str:username>/delete", views.delete_doc, name="delete_doc"),
    path("doctor/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("doctor/<str:username>/appointments/<str:month>", views.CalendarView.as_view(), name="calendar"),
    path("patient/<str:username>/appointments", views.patient_appointments),
    path("patient/<str:username>/appointments/<int:appointment_id>/pay", views.pay_for_appointment),
    path("patient/<str:username>/appointments/<int:appointment_id>/edit", views.edit_appointment, name="edit_appointment"),
    path("patient/<str:username>/appointments/<int:appointment_id>/delete", views.delete_appointment, name="delete_appointment"),
    path("patient/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("forgot_password", views.forgot_password),
    path("patient/<str:username>/prescriptions", views.patient_prescriptions),
    path("patient/<str:username>/prescriptions/add", views.add_prescriptions),
    path("patient/<str:username>/prescriptions/<int:prescription_id>/delete", views.delete_prescriptions, name="delete_prescription"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/patients/add_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Add Appointment</title>
</head>
<body class="bg-light">
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% endif %}
<div class="container">
    <div class="py-5 text-center">
        <h1>Schedule an Appointment</h1>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: 480px; margin-right: 500px">
        <form method="POST">
            {% csrf_token %}
            <div class="col-md-5" style="margin-bottom: 10px">
                <strong>Set a meeting with doctor </strong>
                <strong>{{ form.doctor }}</strong>
            </div>
            <div class="col-md-5" id="patientDiv" style="margin-bottom: 10px">
                <strong>Set a meeting with patient </strong>
                <strong>{{ form.patient }}</strong>
            </div>
            <div class="col-md-5">
                <label class="form-label"><strong> {{ form.date.label }}</strong></label>
                {{ form.date }}
            </div>
            <div class="col-md-5">
                <label class="form-label"><strong> {{ form.time.label }} </strong></label>
                {{ form.time }}
            </div>
            <div class="col-md-5">
                <label class="form-label"> <strong>{{ form.meeting_link.label }}</strong> </label>
                {{ form.meeting_link }}
            </div>

            <div>
                <br>
                <button type="submit" class="btn btn-primary mb-5">Submit</button>
            </div>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

<script>
    document.getElementById("id_doctor").className = "form-select"
    document.getElementById("id_patient").className = "form-select"
    document.getElementById("id_patient").style.width = "360px"
    document.getElementById("id_date").type = "date"
    document.getElementById("id_time").type = "time"
    var inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
    if ("{{supervisor}}" === "False") {
        document.getElementById("patientDiv").style.display = "none"
        document.getElementById("id_patient").value = "{{request.user.id}}"
    }
</script>

templates/patients/add_prescriptions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Add Prescription</title>
</head>
<body class="bg-light">
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% endif %}
<div class="container">
    <div class="py-5 text-center">
        <h1>Fill Prescription</h1>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: 480px; margin-right: 500px">
        <form method="POST">
            {% csrf_token %}
            <div class="col-md-5" style="margin-bottom: 10px">
                <strong>Recommended by doctor </strong>
                <strong>{{ form.doctor }}</strong>
            </div>
            <div class="col-md-5" id="patientDiv" style="margin-bottom: 10px">
                <strong>{{ form.patient }}</strong>
            </div>
            <div class="col-md-5">
                <label class="form-label"><strong> {{ form.date.label }}</strong></label>
                {{ form.date }}
            </div>
            <div class="col-md-5">
                <label class="form-label"> <strong>{{ form.description.label }}</strong> </label>
                {{ form.description }}
            </div>

            <div>
                <br>
                <a href="/patient/{{username}}/appointments"><button type="button" class="btn btn-secondary mb-5">Cancel</button></a>
                <button type="submit" class="btn btn-primary mb-5">Submit</button>
            </div>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

<script>
    document.getElementById("id_doctor").className = "form-select"
    document.getElementById("id_patient").className = "form-select"
    document.getElementById("id_patient").style.width = "360px"
    document.getElementById("id_date").type = "date"
    var inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
    if ("{{supervisor}}" === "False") {
        document.getElementById("patientDiv").style.display = "none"
        document.getElementById("id_patient").value = "{{request.user.id}}"
    }
</script>

templates/patients/appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Appointments</title>
</head>
<body>
{% include "nav_bars/logged_in_nav_bar.html" %}
<div class="p-5">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Patient</th>
            <th scope="col">Doctor</th>
            <th scope="col">Date</th>
            <th scope="col">Time</th>
            <th scope="col">Meeting Link</th>
            <th scope="col">Payment</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for appointment in appointments %}
            <tr>
                <td>{{ appointment.patient }}</td>
                <td>{{ appointment.doctor }}</td>
                <td>{{ appointment.date }}</td>
                <td>{{ appointment.time }}</td>
                <td><a href="//{{ appointment.meeting_link }}">{{ appointment.meeting_link }}</a></td>
                <td><a href="appointments/{{ appointment.pk }}/pay">
                    <button class="btn btn-primary">Pay</button>
                </a></td>
                <td><a href="appointments/{{ appointment.pk }}/edit">
                    <button class="btn btn-primary">Edit</button>
                </a></td>
                <td><a href="appointments/{{ appointment.pk }}/delete">
                    <i class="bi bi-file-x"></i>
                </a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="/patient/{{ request.user.username }}/addappointment">
        <button class="btn btn-primary">Book Appointment</button>
    </a>
</div>
</body>
<footer>
    {% include "nav_bars/footer.html" %}
</footer>
</html>

templates/patients/edit_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Edit Appointment</title>
</head>
<body class="bg-light">
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% endif %}
<div class="container">
    <div class="py-5 text-center">
        <h1>Schedule an Appointment</h1>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: 480px; margin-right: 500px">
        <form method="POST">
            {% csrf_token %}
            <div class="col-md-5" style="margin-bottom: 10px">
                <strong>Set a meeting with doctor </strong>
                <strong>{{ form.doctor }}</strong>
            </div>
            <div class="col-md-5" id="patientDiv" style="margin-bottom: 10px">
                <strong>Set a meeting with patient </strong>
                <strong>{{ form.patient }}</strong>
            </div>
            <div class="col-md-5">
                <label class="form-label"><strong> {{ form.date.label }}</strong></label>
                {{ form.date }}
            </div>
            <div class="col-md-5">
                <label class="form-label"><strong> {{ form.time.label }} </strong></label>
                {{ form.time }}
            </div>
            <div class="col-md-5">
                <label class="form-label"> <strong>{{ form.meeting_link.label }}</strong> </label>
                {{ form.meeting_link }}
            </div>

            <div>
                <br>
                <button type="submit" class="btn btn-primary mb-5">Submit</button>
            </div>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

<script>
    document.getElementById("id_doctor").className = "form-select"
    document.getElementById("id_patient").className = "form-select"
    document.getElementById("id_patient").style.width = "360px"
    document.getElementById("id_date").type = "date"
    document.getElementById("id_time").type = "time"
    var inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
    if ("{{supervisor}}" === "False") {
        document.getElementById("patientDiv").style.display = "none"
        document.getElementById("id_patient").value = "{{request.user.id}}"
    }
</script>

templates/patients/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Edit Profile</title>
</head>
<body class="bg-light">
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% endif %}
<div class="container">
    <div class="py-5 text-center">
        <h1 id="formTitle">Edit Patient's profile</h1>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: auto; margin-right: 100px">
        <form class="row g-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-md-5">
                    <label class="form-label"> {{ field.label }} </label>
                    {{ field }}
                </div>
            {% endfor %}
            <ul class="row" style="margin-left: 15px">
                <li class="col-5">Password must contain at least 8 characters</li>
                <li class="col-5">Password should not include user's info</li>
                <li class="col-5">Password should not be common</li>
                <li class="col-5">Password should not be entirely numeric</li>
            </ul>
            <div>
                <br>
                <button type="submit" class="btn btn-primary">Edit Profile</button>
            </div>
            <hr>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

<script>

    var doctorCheck = document.getElementById("id_is_doctor")
    doctorCheck.style.display = "none"
    document.getElementById("id_security_question").placeholder = "What was the name of your favorite teacher?"
    document.getElementById("id_birthday").type = "date"
    document.getElementById("id_gender").className = "form-select"
    var labels = document.getElementsByTagName('label');
    for (let i = 0; i < labels.length; i++) {
        if (labels[i].innerText.includes("Is doctor")) {
            labels[i].parentElement.style.display = "none";
            break
        }
    }
    var inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
    if (window.location.toString().includes("doctor")) {
        document.getElementById("id_specialization").className = "form-select"
        document.getElementById("formTitle").innerText = "Register Doctor"
        document.getElementById("doctorSignup").innerText = "Are you a patient?"
        document.getElementById("singupLink").href = "/register/patient"
        document.getElementById("singupLink").innerText = "Sign Up here"
        doctorCheck.checked = true
    } else {
        document.getElementById("id_security_question").parentElement.className = "form-group"
        document.getElementById("id_security_question").parentElement.style.width = "83%"
        document.getElementById("id_security_question").className = "form-control"
    }
    document.getElementById("photo-clear_id").className = ""

</script>

templates/patients/pay_for_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Payment</title>
</head>
<body>
{% include "nav_bars/logged_in_nav_bar.html" %}
<div class="text-center mt-5 mb-5">
    <div class="container-fluid py-3">
        <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 mx-auto">
                <div id="pay-invoice" class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h3 class="text-center"><h2>Paying for Appointment</h2>
                                <br>With: Dr. {{ appointment.doctor.username }} on {{ appointment.date }}
                                at {{ appointment.time }}</h3>
                        </div>
                        <hr>
                        <form action="" method="post" novalidate="novalidate" class="needs-validation">


                            <div class="form-group">
                                <label for="cc-number" class="control-label mb-1">Card number</label>
                                <input id="cc-number" placeholder="0000 0000 0000 0000" name="cc-number" type="tel"
                                       class="form-control cc-number identified visa" required autocomplete="off">
                                <span class="invalid-feedback">Enter a valid 12 to 16 digit card number</span>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <div class="form-group">
                                        <label for="cc-exp" class="control-label mb-1">Expiration</label>
                                        <input id="cc-exp" name="cc-exp" type="tel" class="form-control cc-exp" required
                                               placeholder="MM / YY" autocomplete="cc-exp">
                                        <span class="invalid-feedback">Enter the expiration date</span>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <label for="x_card_code" class="control-label mb-1">CVV</label>
                                    <div class="input-group">
                                        <input id="x_card_code" name="x_card_code" type="tel"
                                               class="form-control cc-cvc" required autocomplete="off">
                                        <span class="invalid-feedback order-last">Enter the 3-digit code on back</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="x_name" class="control-label mb-1">Name</label>
                                <input id="x_name" name="x_prom" type="text" class="form-control"
                                       value="{{ request.user.get_full_name }}"
                                       data-val="true" data-val-required="Please enter your name">
                                <span class="help-block" data-valmsg-for="x_name"
                                      data-valmsg-replace="true"></span>
                            </div>
                            <br>
                            <div>
                                <button id="payment-button" type="button" class="btn btn-primary">
                                    <span id="payment-button-amount">Pay</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "nav_bars/footer.html" %}
</body>
</html>

templates/patients/prescriptions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Prescriptions</title>
</head>
<body>
{% include "nav_bars/logged_in_nav_bar.html" %}
<div class="p-5">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Patient</th>
            <th scope="col">Doctor</th>
            <th scope="col">Date</th>
            <th scope="col">Description</th>
        </tr>
        </thead>
        <tbody>
        {% for prescription in prescriptions %}
            <tr>
                <td>{{ prescription.patient }}</td>
                <td>{{ prescription.doctor }}</td>
                <td>{{ prescription.date }}</td>
                <td>{{ prescription.description }}</td>
                <td><a href="prescriptions/{{ prescription.pk }}/delete">
                    <i class="bi bi-file-x"></i>
                </a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
<footer>
    {% include "nav_bars/footer.html" %}
</footer>
</html>

templates/patients/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css">

    <style>
        body {
            background-color: #eee
        }

        .team-button button {
            font-size: 12px;
            width: 180px;
            height: 40px
        }

        .team-projects span {
            font-size: 12px;
            width: 250px;
            height: 40px;
            border: 1px solid #d4d2d2;
            background-color: #eee;
            border-radius: 4px;
            padding: 10px 23px;
        }
    </style>
    <title>Patient</title>
</head>
<body>
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% endif %}
<div class="container d-flex justify-content-center align-items-center mt-5 mb-5">
    <div class="card mb-5" style="width: 40rem;">
        <div class="p-2">
            <div class="d-flex flex-row ml-5 mt-4">
                {% if patient.photo %}
                    <img class="rounded-circle" src="{{ patient.photo.url }}" width="80" height="80" alt="PP">
                {% else %}
                    <img src="../../media/default_pic.jpg" class="rounded-circle" width="70" alt="Default PP">
                {% endif %}
                <div class="d-flex flex-column ml-5 mt-4"><span
                        style="font-weight: bold; font-size: 25px">Patient Profile: {{ patient.first_name }} {{ patient.last_name }}</span>
                </div>
            </div>
            <div class="mt-4"><span class="ml-2" style="font-weight: bold">Birth Date</span>
                <div class="mt-3 team-projects d-flex justify-content-between px-2"><span>{{ patient.birthday }}</span>
                </div>
            </div>
        </div>
        <div class=" mt-3 mb-3"><span class="ml-2 mb-3" style="font-weight: bold">Personal Information</span>
            <hr class="m-0 mt-1">
        </div>
        <div class="d-flex flex-row justify-content-between px-3">
            <div class="d-flex flex-column ml-2"><span>Phone</span>
                <div class="mt-2 team-projects d-flex justify-content-between px-0">
                    <span>{{ patient.phone_number }}</span></div>
            </div>
            <div class="d-flex flex-column ml-2"><span>Email</span>
                <div class="mt-2 team-projects d-flex justify-content-between"><span>{{ patient.email }}</span>
                </div>
            </div>
        </div>
        <div class="d-flex flex-row justify-content-between px-3 mb-3 mt-3">
            <div class="d-flex flex-column ml-2"><span>Allergies</span>
                <div class="mt-2 team-projects d-flex justify-content-between px-0"><span>{{ patient.allergies }}</span>
                </div>
            </div>
            <div class="d-flex flex-column ml-2"><span>Medical Issues</span>
                <div class="mt-2 team-projects d-flex justify-content-between px-0">
                    <span>{{ patient.medical_issues }}</span></div>
            </div>
        </div>
        <div class="mt-4 mb-3"><span class="ml-3" style="font-weight: bold">Edit Profile</span>
            <div class="mt-2 team-button d-flex justify-content-between px-3">
                <a href="{% url 'EHMSAPP:edit_profile' patient.username %}">
                    <button class="btn btn-primary ml-1">Edit</button>
                </a>
            </div>
            <div class="mt-2 team-button d-flex justify-content-between px-3">
                <a href="{% url 'EHMSAPP:delete_profile' patient.username %}">
                    <button class="btn btn-primary ml-1">Delete</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>