EHMS/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "EHMSAPP"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("EHMSAPP.urls")),
]

EHMSAPP/urls.py
from django.urls import path

from EHMSAPP import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "EHMSAPP"

urlpatterns = [
    path("", views.home),
    path("appointments", views.supervisor_appointments),
    path("patients", views.supervisor_patients),
    path("prescriptions", views.supervisor_prescriptions),
    path("login/", views.login_request),
    path("doctors/", views.get_all_doctors),
    path("logout/", views.logout_request),
    path("register/doctor", views.register_doctor),
    path("register/patient", views.register_patient),
    path("doctor/<str:username>", views.doctor_profile, name="doctor_profile"),
    path("patient/<str:username>", views.patient_profile, name="patient_profile"),
    path("patient/<str:username>/edit", views.edit_profile, name="edit_profile"),
    path("patient/<str:username>/delete", views.delete_profile, name="delete_profile"),
    path("doctor/<str:username>/edit", views.edit_doc, name="edit_doc"),
    path("doctor/<str:username>/delete", views.delete_doc, name="delete_doc"),
    path("doctor/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("doctor/<str:username>/appointments/<str:month>", views.CalendarView.as_view(), name="calendar"),
    path("patient/<str:username>/appointments", views.patient_appointments),
    path("patient/<str:username>/appointments/<int:appointment_id>/pay", views.pay_for_appointment),
    path("patient/<str:username>/appointments/<int:appointment_id>/edit", views.edit_appointment, name="edit_appointment"),
    path("patient/<str:username>/appointments/<int:appointment_id>/delete", views.delete_appointment, name="delete_appointment"),
    path("patient/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("forgot_password", views.forgot_password),
    path("patient/<str:username>/prescriptions", views.patient_prescriptions),
    path("patient/<str:username>/prescriptions/add", views.add_prescriptions),
    path("patient/<str:username>/prescriptions/<int:prescription_id>/delete", views.delete_prescriptions, name="delete_prescription"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/supervisor/appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Appointments</title>
</head>
<body>
{% include "nav_bars/supervisor_nav_bar.html" %}
<div class="p-5">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Patient</th>
            <th scope="col">Doctor</th>
            <th scope="col">Date</th>
            <th scope="col">Time</th>
            <th scope="col">Meeting Link</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for appointment in appointments %}
            <tr>
                <td>{{ appointment.patient }}</td>
                <td>{{ appointment.doctor }}</td>
                <td>{{ appointment.date }}</td>
                <td>{{ appointment.time }}</td>
                <td><a href="//{{ appointment.meeting_link }}">{{ appointment.meeting_link }}</a></td>
                <td><a href="{% url 'EHMSAPP:edit_appointment' appointment.patient.username appointment.pk %}">
                    <button class="btn btn-primary">Edit</button>
                </a></td>
                <td><a href="{% url 'EHMSAPP:delete_appointment' appointment.patient.username appointment.pk %}">
                    <i class="bi bi-file-x"></i>
                </a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
<footer>
    {% include "nav_bars/footer.html" %}
</footer>
</html>

templates/supervisor/patients.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <style>

        .X {
            margin: auto;
            padding: 1% 2%;
            max-width: 1440px;
            border-radius: 5px;
            background: #ecf0f1;
            box-shadow: 0 2px 6px 0 rgba(0, 0, 0, .3);
        }

        h1, h2, h3 {
            text-align: center;
            font-family: 'Arial', sans-serif;
        }


        /*SG = style grid*/
        .SG {
            margin: 0;
            padding: 0;
            text-align: center;
        }

        .SG .sgLi {
            min-width: 24%;
            margin: 2% .35%;
            display: inline-flex;
            box-shadow: 0 2px 4px rgba(0, 0, 0, .2);
        }

        .SG .sgLi:hover {
            box-shadow: 0 5px 10px rgba(0, 0, 0, .15);
        }

        .SG .box {
            width: 100%;
            height: 100vh;
            padding: 4% 2%;
            background: #fff;
            min-height: 200px;
            max-height: 220px;
            box-sizing: border-box;
        }
    </style>
    <title>Patients</title>
</head>
<body>
{% include "nav_bars/supervisor_nav_bar.html" %}
<div class="X">
    <ul class="SG">
        {% for patient in patients %}
            <li class="sgLi">
                <div class="box">
                    <h4>Patient: {{ patient.first_name }} {{ patient.last_name }}</h4>
                    <h5 style="color: silver">{{ patient.specialization }}</h5>
                    <div style="padding-top: 4%;">
                        {% if patient.photo %}
                            <img class="rounded-circle" src="{{ patient.photo.url }}" width="80" height="80" alt="PP">
                        {% else %}
                            <img src="../../media/default_pic.jpg" class="rounded-circle" width="70" alt="Default PP">
                        {% endif %}
                        <a href="{% url 'EHMSAPP:patient_profile' patient.username %}">
                            <button class="btn btn-primary ml-1">View Patient's Profile</button>
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>
<script>
    document.getElementById("id_specialization").className = "form-select"
    document.getElementById("id_specialization").style.width = "200px"
    document.getElementById("id_specialization").style.display = "inline"
</script>

templates/supervisor/prescriptions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Prescriptions</title>
</head>
<body>
{% include "nav_bars/supervisor_nav_bar.html" %}
<div class="p-5">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Patient</th>
            <th scope="col">Doctor</th>
            <th scope="col">Date</th>
            <th scope="col">Description</th>
        </tr>
        </thead>
        <tbody>
        {% for prescription in prescriptions %}
            <tr>
                <td>{{ prescription.patient }}</td>
                <td>{{ prescription.doctor }}</td>
                <td>{{ prescription.date }}</td>
                <td>{{ prescription.description }}</td>
                <td><a href="{% url 'EHMSAPP:delete_prescription' prescription.patient.username prescription.pk %}">
                    <i class="bi bi-file-x"></i>
                </a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
<footer>
    {% include "nav_bars/footer.html" %}
</footer>
</html>