EHMS/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "EHMSAPP"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("EHMSAPP.urls")),
]

EHMSAPP/urls.py
from django.urls import path

from EHMSAPP import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "EHMSAPP"

urlpatterns = [
    path("", views.home),
    path("appointments", views.supervisor_appointments),
    path("patients", views.supervisor_patients),
    path("prescriptions", views.supervisor_prescriptions),
    path("login/", views.login_request),
    path("doctors/", views.get_all_doctors),
    path("logout/", views.logout_request),
    path("register/doctor", views.register_doctor),
    path("register/patient", views.register_patient),
    path("doctor/<str:username>", views.doctor_profile, name="doctor_profile"),
    path("patient/<str:username>", views.patient_profile, name="patient_profile"),
    path("patient/<str:username>/edit", views.edit_profile, name="edit_profile"),
    path("patient/<str:username>/delete", views.delete_profile, name="delete_profile"),
    path("doctor/<str:username>/edit", views.edit_doc, name="edit_doc"),
    path("doctor/<str:username>/delete", views.delete_doc, name="delete_doc"),
    path("doctor/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("doctor/<str:username>/appointments/<str:month>", views.CalendarView.as_view(), name="calendar"),
    path("patient/<str:username>/appointments", views.patient_appointments),
    path("patient/<str:username>/appointments/<int:appointment_id>/pay", views.pay_for_appointment),
    path("patient/<str:username>/appointments/<int:appointment_id>/edit", views.edit_appointment, name="edit_appointment"),
    path("patient/<str:username>/appointments/<int:appointment_id>/delete", views.delete_appointment, name="delete_appointment"),
    path("patient/<str:username>/addappointment", views.add_appointment, name="add_appointment"),
    path("forgot_password", views.forgot_password),
    path("patient/<str:username>/prescriptions", views.patient_prescriptions),
    path("patient/<str:username>/prescriptions/add", views.add_prescriptions),
    path("patient/<str:username>/prescriptions/<int:prescription_id>/delete", views.delete_prescriptions, name="delete_prescription"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/all_doctors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <style>

        .X {
            margin: auto;
            padding: 1% 2%;
            max-width: 1440px;
            border-radius: 5px;
            background: #ecf0f1;
            box-shadow: 0 2px 6px 0 rgba(0, 0, 0, .3);
        }

        h1, h2, h3 {
            text-align: center;
            font-family: 'Arial', sans-serif;
        }


        /*SG = style grid*/
        .SG {
            margin: 0;
            padding: 0;
            text-align: center;
        }

        .SG .sgLi {
            min-width: 24%;
            margin: 2% .35%;
            display: inline-flex;
            box-shadow: 0 2px 4px rgba(0, 0, 0, .2);
        }

        .SG .sgLi:hover {
            box-shadow: 0 5px 10px rgba(0, 0, 0, .15);
        }

        .SG .box {
            width: 100%;
            height: 100vh;
            padding: 4% 2%;
            background: #fff;
            min-height: 200px;
            max-height: 220px;
            box-sizing: border-box;
        }
    </style>
    <title>Doctors</title>
</head>
<body>
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% elif request.user.is_authenticated %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_out_nav_bar.html" %}
{% endif %}
<div class="X">
    <ul class="SG">
        <form id="filterForm" method="post">
            {% for field in form %}
                {% csrf_token %}
                <label class="form-label"> {{ field.label }} </label>
                {{ field }}
            {% endfor %}
            <button class="btn btn-outline-success">Submit</button>
        </form>
        {% for doctor in doctors %}
            <li class="sgLi">
                <div class="box">
                    <h4>Dr. {{ doctor.first_name }} {{ doctor.last_name }}</h4>
                    <h5 style="color: silver">{{ doctor.specialization }}</h5>
                    <div style="padding-top: 4%;">
                        {% if doctor.photo %}
                            <img class="rounded-circle" src="{{ doctor.photo.url }}" width="80" height="80" alt="PP">
                        {% else %}
                            <img src="../../media/default_pic.jpg" class="rounded-circle" width="70" alt="Default PP">
                        {% endif %}
                        <a href="{% url 'EHMSAPP:doctor_profile' doctor.username %}">
                            <button class="btn btn-primary ml-1">View Doctor's Profile</button>
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>
<script>
    document.getElementById("id_specialization").className = "form-select"
    document.getElementById("id_specialization").style.width = "200px"
    document.getElementById("id_specialization").style.display = "inline"
</script>

templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Forgot Password</title>
</head>
<body>
{% include "nav_bars/logged_out_nav_bar.html" %}
<div class="container mb-5">
    <div class="py-5 text-center">
        <h1>Forgot Password</h1>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: 480px; margin-right: 500px">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-md-5">
                    <label class="form-label"> {{ field.label }} </label>
                    {{ field }}
                </div>
            {% endfor %}
            <div>
                <br>
                <button type="submit" class="btn btn-primary mb-5">Submit</button>
            </div>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>
<script>
    {% if changed %}
        alert("Password reset to: default")
        window.location.href = '/login';
    {% endif %}
    var inputs = document.getElementsByTagName('input');
    document.getElementById("id_security_question").placeholder = "What was the name of your favorite teacher?"
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
</script>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Home</title>
</head>
<body>
{% if supervisor %}
    {% include "nav_bars/supervisor_nav_bar.html" %}
{% elif request.user.is_authenticated %}
    {% include "nav_bars/logged_in_nav_bar.html" %}
{% else %}
    {% include "nav_bars/logged_out_nav_bar.html" %}
{% endif %}
<div class="tex-center ml-3 p-3">
    <h1 style="color: forestgreen; text-align: center">E-Healthcare Management System</h1>
    <h3 style="text-align: center">Our lives dedicated to yours</h3>
    <img class="rounded mx-auto d-block" width="500" height="500" src="../media/home.gif" alt="home">
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Login</title>
</head>
<body class="bg-light">
{% include "nav_bars/logged_out_nav_bar.html" %}
<div class="container">
    <div class="py-5 text-center">
        <h1>Login</h1>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: 480px; margin-right: 500px">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-md-5">
                    <label class="form-label"> {{ field.label }} </label>
                    {{ field }}
                </div>
            {% endfor %}
            <div class=""><a href="/forgot_password">Forgot Password </a></div>
            <div>
                <br>
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
            <hr style="width: 370px">
            <div class="mb-5"><span>Don’t have an account? </span> <a href="/register/patient"> Sign Up </a></div>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

<script>
    var inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
</script>

templates/register_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Register</title>
</head>
<body class="bg-light">
{% include "nav_bars/logged_out_nav_bar.html" %}
<div class="container">
    <div class="py-5 text-center">
        <h1 id="formTitle">Register Patient</h1>
        <span id="doctorSignup">Are you a doctor?</span> <a id="singupLink" href="/register/doctor">Sign Up here</a>
    </div>
    <div class="col-md-7 col-lg-8" style="margin-left: auto; margin-right: 100px">
        <form class="row g-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-md-5">
                    <label class="form-label"> {{ field.label }} </label>
                    {{ field }}
                </div>
            {% endfor %}
            <ul class="row" style="margin-left: 15px">
                <li class="col-5">Password must contain at least 8 characters</li>
                <li class="col-5">Password should not include user's info</li>
                <li class="col-5">Password should not be common</li>
                <li class="col-5">Password should not be entirely numeric</li>
            </ul>
            <div>
                <br>
                <button type="submit" class="btn btn-primary">Create Account</button>
            </div>
            <hr>
            <div class="mb-5"><span>By signing up, you agree to the <a
                    href="/terms/">Terms of Service</a></span>
            </div>
        </form>
    </div>
</div>
{% include "nav_bars/footer.html" %}
</body>
</html>

<script>

    var doctorCheck = document.getElementById("id_is_doctor")
    doctorCheck.style.display = "none"
    document.getElementById("id_security_question").placeholder = "What was the name of your favorite teacher?"
    document.getElementById("id_birthday").type = "date"
    document.getElementById("id_gender").className = "form-select"
    var labels = document.getElementsByTagName('label');
    for (let i = 0; i < labels.length; i++) {
        if (labels[i].innerText.includes("Is doctor")) {
            labels[i].parentElement.style.display = "none";
            break
        }
    }
    var inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        inputs[i].className = "form-control";
    }
    if (window.location.toString().includes("doctor")) {
        document.getElementById("id_specialization").className = "form-select"
        document.getElementById("formTitle").innerText = "Register Doctor"
        document.getElementById("doctorSignup").innerText = "Are you a patient?"
        document.getElementById("singupLink").href = "/register/patient"
        document.getElementById("singupLink").innerText = "Sign Up here"
        doctorCheck.checked = true
    } else {
        document.getElementById("id_security_question").parentElement.className = "form-group"
        document.getElementById("id_security_question").parentElement.style.width = "83%"
        document.getElementById("id_security_question").className = "form-control"
    }

</script>